# Generated by Django 2.1.4 on 2018-12-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_platform', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('v', 'Visible'), ('h', 'Hidden')], default='v', max_length=1),
        ),
    ]
