# Generated by Django 2.1.4 on 2018-12-24 21:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('email', models.CharField(default='-', max_length=50, verbose_name='Электронная почта')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='-', max_length=50, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(default='-', max_length=50, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(blank=True, to='book_book.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_book.Supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_book.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_book.Product', verbose_name='Товар'),
        ),
    ]
