# Generated by Django 2.1.4 on 2018-12-24 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_book', '0002_auto_20181224_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(default='-', max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Электронная почта'),
        ),
    ]
