# Generated by Django 2.1.4 on 2018-12-24 23:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_book', '0003_auto_20181224_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='staffer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book_book.Staffer', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='staffer',
            name='email',
            field=models.CharField(default='-', max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(default='-', max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Электронная почта'),
        ),
    ]
